// IMPORTING THE EXPRESS MODULE
import express from "express";

// CREATING AN EXPRESS OBJECT AND STORING IT IN A VARIABLE 
const app = express();

// CREATING A CALLBACK FUNCTION FUNCTION WHICH WILL BE 
// INVOKED WHENEVER THE USER LOADS THE URL FOR THE APPLICATION
app.get("/", (req, res) => res.send("Hello World"));

// NOTE: THE RES PARAMETER IS PROVIDED BY THE REQUEST MODULE 
// WHICH IS USED TO SEND THE RESPONSE TO THE CLIENT

// ESTABLISHING THE SERVER CONNECTION BY ASSIGNING THE PORT
const port = process.env.PORT || 8080;
app.listen(port, () => console.log("Listening on port ${port}..."))

// NOW THE APPLICATION WILL LISTEN TO CLIENT REQUESTS ON PORT 8080






