// IMPORTING THE EXPRESS MODULE TO THE EXPRESS VARIABLE
import express from "express";

// INSTANTIATING AN EXPRESS OBJECT AND STORING IT IN A VARIABLE 
const app = express();

// INSTRUCTING THE APPLICATION TO LISTEN FOR GET REQUESTS ON THE / PATH
app.get("/", (req, res) => res.send("Hello World"));

// THE CALLBACK FUNCTION WILL BE INVOKED WHENEVER THE USER LOADS THE URL FOR THE APPLICATION

// NOTE: THE RES PARAMETER IS PROVIDED BY THE REQUEST MODULE 
// WHICH IS USED TO SEND THE RESPONSE TO THE CLIENT

// ESTABLISHING THE SERVER CONNECTION BY ASSIGNING THE PORT
// const port = process.env.PORT || 8080;
app.listen(8080, () => console.log("Server Ready"))

// NOW THE APPLICATION WILL LISTEN TO CLIENT REQUESTS ON PORT 8080






